#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely and creates a PID file
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
